# 🎯 Definição das Medidas de Frequência

Imagine que você coletou dados de satisfação de pacientes.

A pergunta não é só:
"Qual foi a resposta?"

Mas sim:
- Quantos responderam cada categoria?
- Qual proporção está satisfeita?
- Existe concentração em algum grupo?

É isso que as medidas de frequência respondem.

#❤️ Criando um dataset de exemplo em saúde

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "paciente": range(1, 21),
    "satisfacao": [
        "Muito Insatisfeito", "Satisfeito", "Neutro", "Insatisfeito", "Neutro",
        "Muito Insatisfeito", "Satisfeito", "Neutro", "Muito satisfeito", "Muito satisfeito",
        "Muito satisfeito", "Insatisfeito", None, "Satisfeito", None,
        "Satisfeito", "Satisfeito", "Insatisfeito", "Neutro", "Neutro"
    ]
})

df

    paciente          satisfacao
0          1  Muito Insatisfeito
1          2          Satisfeito
2          3              Neutro
3          4        Insatisfeito
4          5              Neutro
5          6  Muito Insatisfeito
6          7          Satisfeito
7          8              Neutro
8          9    Muito satisfeito
9         10    Muito satisfeito
10        11    Muito satisfeito
11        12        Insatisfeito
12        13                None
13        14          Satisfeito
14        15                None
15        16          Satisfeito
16        17          Satisfeito
17        18        Insatisfeito
18        19              Neutro
19        20              Neutro

👉 Aqui já introduz um ponto importante: existem dados faltantes

# 📊 Cálculo das medidas de frequência

##### **Frequência absoluta(ni)**

A frequência absoluta indica quantas vezes cada categoria aparece.

In [ ]:
freq_abs = df["satisfacao"].value_counts(dropna=False)
freq_abs

satisfacao
Satisfeito            5
Neutro                5
Muito satisfeito      3
Insatisfeito          3
Muito Insatisfeito    2
None                  2
Name: count, dtype: int64

👉 Interpretação: quantos pacientes estão em cada categoria

##### **Frequência relativa (fi)**

Mostra a proporção de cada categoria em relação ao total.

In [ ]:
freq_rel = df["satisfacao"].value_counts(normalize=True, dropna=False)
(freq_rel * 100).round(1)

satisfacao
Satisfeito            25.0
Neutro                25.0
Muito satisfeito      15.0
Insatisfeito          15.0
Muito Insatisfeito    10.0
None                  10.0
Name: proportion, dtype: float64

##### **Percentual válido**

Considera apenas os dados válidos (exclui faltantes).

In [ ]:
df_validos = df["satisfacao"].dropna()

freq_rel_valida = df_validos.value_counts(normalize=True)
(freq_rel_valida * 100).round(1)

satisfacao
Satisfeito            27.8
Neutro                27.8
Insatisfeito          16.7
Muito satisfeito      16.7
Muito Insatisfeito    11.1
Name: proportion, dtype: float64

👉 Interpretação: mais fiel quando há missing

##### **Frequência acumulada**

Mostra o acúmulo das frequências ao longo das categorias.

In [ ]:
freq_ord = df_validos.value_counts().sort_index()

freq_acum = freq_ord.cumsum()
freq_rel_acum = (freq_ord / freq_ord.sum()).cumsum()

print("Frequência acumulada:")
print(freq_acum)

print("\nFrequência relativa acumulada (%):")
print((freq_rel_acum * 100).round(1))

Frequência acumulada:
satisfacao
Insatisfeito           3
Muito Insatisfeito     5
Muito satisfeito       8
Neutro                13
Satisfeito            18
Name: count, dtype: int64

Frequência relativa acumulada (%):
satisfacao
Insatisfeito           16.7
Muito Insatisfeito     27.8
Muito satisfeito       44.4
Neutro                 72.2
Satisfeito            100.0
Name: count, dtype: float64

##### **Tabela completa**

In [ ]:
tabela_freq = pd.DataFrame({
    "ni": df["satisfacao"].value_counts(dropna=False),
})

tabela_freq["fi (%)"] = (tabela_freq["ni"] / len(df) * 100).round(1)

tabela_freq_validos = df["satisfacao"].dropna().value_counts()

tabela_freq["Fi acumulada (%)"] = tabela_freq["fi (%)"].cumsum()

tabela_freq["fi válida (%)"] = (
    tabela_freq_validos / tabela_freq_validos.sum() * 100
).round(1)

tabela_freq

                    ni  fi (%)  Fi acumulada (%)  fi válida (%)
satisfacao
Satisfeito           5    25.0              25.0           27.8
Neutro               5    25.0              50.0           27.8
Muito satisfeito     3    15.0              65.0           16.7
Insatisfeito         3    15.0              80.0           16.7
Muito Insatisfeito   2    10.0              90.0           11.1
None                 2    10.0             100.0            NaN

# 🧠 Interpretação

Como interpretar?

* Frequência absoluta → volume real
* Frequência relativa → proporção
* Percentual válido → análise sem viés de missing
* Frequência acumulada → concentração ao longo das categorias

Perguntas que você consegue responder:

* A maioria está satisfeita?
* Existe polarização?
* Há muitos dados faltantes?

# 🔗 Conexão com saúde

Medidas de frequência são usadas para:

* Distribuição de diagnósticos (CID)
* Origem dos pacientes
* Classificação de risco
* Satisfação do paciente (CSAT)
* Perfil epidemiológico

Elas são o primeiro passo antes de qualquer análise mais complexa.

# 🔥 Takeaway

Se tiver que levar uma coisa dessa aula

- Frequência é a forma mais simples e poderosa de entender dados
- Sempre verifique dados faltantes
- Percentual válido muda a interpretação
- Frequência acumulada ajuda a entender concentração

Antes de qualquer análise:
→ faça uma tabela de frequência